# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1a5df82b-f20b-4323-a959-b6cad2c9b5a0";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-ce3fc47b-bc72-41b7-859d-04ffa2544b86".device = "/dev/disk/by-uuid/ce3fc47b-bc72-41b7-859d-04ffa2544b86";

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/e64cfd8a-053c-4a7f-b359-fc3c6afa1ca8";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-4eac6eca-6474-433e-abab-2b7614de3a86".device = "/dev/disk/by-uuid/4eac6eca-6474-433e-abab-2b7614de3a86";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/58BF-2E43";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/570b01dc-0ad2-4214-9cf0-14c77b895cc2";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-f67c60a3-a2bc-47c9-8c70-8651cdc9e246".device = "/dev/disk/by-uuid/f67c60a3-a2bc-47c9-8c70-8651cdc9e246";

  swapDevices =
    [ { device = "/dev/disk/by-uuid/d6103dd1-a745-486b-b2ee-07724fb92379"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
